image: docker-registry.booking.com/itsba/azure-deploy
stages:
   - build
   - deploy
  
build:
  stage: build
  tags:
    - docker
  script: 
     - /root/dotnet/dotnet build
     - cd UnitTest
     - /root/dotnet/dotnet test UnitTest.csproj



deploy-nuget:
  stage: deploy
  tags:
    - win-ps
  script: 
    - cd Booking.Common.Http
    - mkdir c:\temp\
    - $date=Get-Date -format yyyy.M.dHHmm
    - $replacedPackageValue="<PackageVersion>1."+$date+"</PackageVersion>"
    - $contentsOfFile=(Get-Content Booking.Common.Http.csproj).replace('<PackageVersion>1.0.0</PackageVersion>', $replacedPackageValue) | set-content | Booking.Common.Http.csproj

    - dotnet pack Booking.Common.Http.csproj --configuration Release --output c:\temp
    - cd c:\temp
    - dotnet nuget push *.nupkg -k "4d0eae47-22b8-3c85-8b1c-b9bba1b1de36" -s https://nexus.booking.com/nexus/service/local/nuget/nuget-releases/ 