image: docker-registry.booking.com/itsba/azure-deploy
stages:
   - build
   - deploy
  
build:
  stage: build
  tags:
    - docker
  script: 
     - /root/dotnet/dotnet build
     - cd UnitTest
     - /root/dotnet/dotnet test UnitTest.csproj


deploy-nuget:
  stage: deploy
  tags:
    - docker 
  script: 
    
    - mkdir /root/nupkgs
    - /root/dotnet/dotnet pack Booking.Common.Rest/Booking.Common.Rest.csproj --configuration Release --output /root/nupkgs /p:PackageVersion="1.$(date -d 'now' '+%Y.%m.%d%H%M')"
    - /root/dotnet/dotnet pack Booking.Common.HttpClient.Extensions/Booking.Common.HttpClient.Extensions.csproj --configuration Release --output /root/nupkgs /p:PackageVersion="1.$(date -d 'now' '+%Y.%m.%d%H%M')"
    - for fn in `find /root/nupkgs/ -name "*.nupkg"`; do
            /root/dotnet/dotnet nuget push $fn -k $PUBLICNUGETKEY -s https://api.nuget.org/v3/index.json &
      done
    - wait
